# Autogenerated file
def render(*a, **d):
    yield """<div class=\"container-sm text-center mt-3 mb-3\"> <div class=\"modal fade\" id=rfidModal  tabindex=-1  aria-labelledby=rfidModalLabel  aria-hidden=true ></div> <div id=rfidBtn ></div> </div>"""
